# https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup
liquor_sales: # profile name. 
# This is where dbt looks for from dbt_project.yml -> find the named profile here. 
# Can also be overwritten by dbt run --profiles. See dbt run --help for more info
  outputs:
    dev:
      dataset: liquor_demo
      job_execution_timeout_seconds: 300
      job_retries: 2
      location: US
      method: oauth
      priority: interactive
      project: "<YOUR-GCP-PROJECT-ID>" # GCP project id
      threads: 1
      type: bigquery
  target: dev # default target for profile, points to 1 of the output above 
  # Usually we use 'dev' for development and 'prod' for production
  # define target in dbt CLI via --target
  config:
    send_anonymous_usage_stats: False